### PR TITLE
rename main file to allow importing properly

### PR DESCRIPTION
**Pull request by xdumaine**
Is there something special about the `jest-preset.js` filename? oddly this repo seems to work in some projects, but it's failing on not finding index.js in others. Maybe another dep version issue.

### CODE REVIEW

**Comment by smolster** [comment]
Hmm...it seems possible that Node versions could make a difference here? Maybe @DavidTanner will know something about that.

**Comment by DavidTanner** [comment]
@xdumaine I'm guessing that it has more to do with jest versions.  According to the [documentation:](https://jestjs.io/docs/configuration#preset-string)

```
A preset that is used as a base for Jest's configuration. A preset should point to an npm module that has a jest-preset.json, jest-preset.js, jest-preset.cjs or jest-preset.mjs file at the root.
```

**Review by DavidTanner — CHANGES_REQUESTED** [review]
This will break modern jest projects

**Comment by DavidTanner** [comment]
If you are wanting to `require` the file, then you can do that by name.

**Comment by DavidTanner** [comment]
https://github.com/lifeomic/user-service/blob/56f4be37e3a4bcb9acc33630d7ec9e2d7c75ad21/jest.config.js#L2

**Comment by xdumaine** [comment]
Thank you that's what I was missing - jest 27.x

**Comment by DavidTanner** [comment]
I think it was also in 26, but I can't find it right now.

**Pull request closed without merging**
